extends: eslint:recommended
parserOptions:
  ecmaVersion: 9
env:
  es6: true
  node: true
rules:
  eqeqeq: error
  no-floating-decimal: error
  no-var: error
  no-implicit-coercion: error
  no-multi-spaces: error
  no-useless-return: error
  no-undef-init: error
  no-trailing-spaces: error
  no-unneeded-ternary: error
  no-whitespace-before-property: error
  nonblock-statement-body-position: error
  space-infix-ops: error
  space-unary-ops: error
  switch-colon-spacing: error
  arrow-body-style: error
  arrow-spacing: error
  generator-star-spacing: error
  no-useless-computed-key: error
  no-useless-rename: error
  new-cap: error
  no-lonely-if: error
  no-console: off
  multiline-comment-style: error
  object-shorthand: error
  prefer-const: error
  prefer-spread: error
  prefer-template: error
  rest-spread-spacing: error
  sort-imports: error
  template-curly-spacing: error
  yield-star-spacing: error
  yoda:
    - error
    - never
  curly:
    - error
    - multi-line
    - consistent
  semi:
    - error
    - never
  quotes:
    - error
    - single
    - avoidEscape: true
  dot-location:
    - error
    - property
  array-bracket-spacing:
    - error
    - never
  array-bracket-newline:
    - error
    - consistent
  block-spacing:
    - error
    - always
  brace-style:
    - error
    - 1tbs
  comma-dangle:
    - error
    - always-multiline
  comma-style:
    - error
    - last
  computed-property-spacing:
    - error
    - never
  func-call-spacing:
    - error
    - never
  function-paren-newline:
    - error
    - multiline
  implicit-arrow-linebreak:
    - error
    - beside
  indent:
    - error
    - 2
  key-spacing:
    - error
    - afterColon: true
      beforeColon: false
      mode: strict
  keyword-spacing:
    - error
    - before: true
      after: true
  line-comment-position:
    - error
    - above
  linebreak-style:
    - error
    - unix
  lines-between-class-members:
    - error
    - always
  no-multiple-empty-lines:
    - error
    - max: 2
  object-curly-newline:
    - error
    - multiline: true
      consistent: true
  object-curly-spacing:
    - error
    - always
  one-var-declaration-per-line:
    - error
    - initializations
  padded-blocks:
    - error
    - never
  quote-props:
    - error
    - as-needed
  space-before-blocks:
    - error
    - always
  space-before-function-paren:
    - error
    - never
  space-in-parens:
    - error
    - never
  spaced-comment:
    - error
    - always
  arrow-parens:
    - error
    - as-needed
