mili:
  version: 3.2.0
template:
  repository: 'https://github.com/Val-istar-Guo/component-template.git'
  version: 2.1.0
answers:
  ci: true
  standardVersion: true
  lint: true
  lock: false
  package: NodeJS
